name: meerkat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  envied: ^0.5.4+1
  fl_chart: ^0.67.0
  collection: ^1.18.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  fast_immutable_collections: ^10.2.4
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0

dependency_overrides:
  fl_chart:
    git: https://github.com/ttoino/fl_chart.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  retrofit_generator: ^8.1.0
  envied_generator: ^0.5.4+1

flutter:
  generate: true

  uses-material-design: true
