on:
  push:
    branches:
      - main
  pull_request:

env:
  JAVA_VERSION: 17

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Format
        run: dart format --set-exit-if-changed .

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Lint
        run: flutter analyze .

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: Generate code
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Test
        run: flutter test --coverage